# Generated by Django 4.2.23 on 2025-07-29 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_1', models.CharField(max_length=100, verbose_name='Filme favorito #1')),
                ('filme_2', models.CharField(max_length=100, verbose_name='Filme favorito #2')),
                ('filme_3', models.CharField(max_length=100, verbose_name='Filme favorito #3')),
                ('filme_4', models.CharField(max_length=100, verbose_name='Filme favorito #4')),
                ('filme_5', models.CharField(max_length=100, verbose_name='Filme favorito #5')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField(default=datetime.datetime(2025, 7, 29, 7, 20, 13, 231414), verbose_name='Publicado em')),
            ],
        ),
    ]
